require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe EvidencesController do

  def mock_evidence(stubs={})
    @mock_evidence ||= mock_model(Evidence, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all evidences as @evidences" do
      Evidence.stub(:all) { [mock_evidence] }
      get :index
      assigns(:evidences).should eq([mock_evidence])
    end
  end

  describe "GET show" do
    it "assigns the requested evidence as @evidence" do
      Evidence.stub(:find).with("37") { mock_evidence }
      get :show, :id => "37"
      assigns(:evidence).should be(mock_evidence)
    end
  end

  describe "GET new" do
    it "assigns a new evidence as @evidence" do
      Evidence.stub(:new) { mock_evidence }
      get :new
      assigns(:evidence).should be(mock_evidence)
    end
  end

  describe "GET edit" do
    it "assigns the requested evidence as @evidence" do
      Evidence.stub(:find).with("37") { mock_evidence }
      get :edit, :id => "37"
      assigns(:evidence).should be(mock_evidence)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created evidence as @evidence" do
        Evidence.stub(:new).with({'these' => 'params'}) { mock_evidence(:save => true) }
        post :create, :evidence => {'these' => 'params'}
        assigns(:evidence).should be(mock_evidence)
      end

      it "redirects to the created evidence" do
        Evidence.stub(:new) { mock_evidence(:save => true) }
        post :create, :evidence => {}
        response.should redirect_to(evidence_url(mock_evidence))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved evidence as @evidence" do
        Evidence.stub(:new).with({'these' => 'params'}) { mock_evidence(:save => false) }
        post :create, :evidence => {'these' => 'params'}
        assigns(:evidence).should be(mock_evidence)
      end

      it "re-renders the 'new' template" do
        Evidence.stub(:new) { mock_evidence(:save => false) }
        post :create, :evidence => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested evidence" do
        Evidence.stub(:find).with("37") { mock_evidence }
        mock_evidence.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :evidence => {'these' => 'params'}
      end

      it "assigns the requested evidence as @evidence" do
        Evidence.stub(:find) { mock_evidence(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:evidence).should be(mock_evidence)
      end

      it "redirects to the evidence" do
        Evidence.stub(:find) { mock_evidence(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(evidence_url(mock_evidence))
      end
    end

    describe "with invalid params" do
      it "assigns the evidence as @evidence" do
        Evidence.stub(:find) { mock_evidence(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:evidence).should be(mock_evidence)
      end

      it "re-renders the 'edit' template" do
        Evidence.stub(:find) { mock_evidence(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested evidence" do
      Evidence.stub(:find).with("37") { mock_evidence }
      mock_evidence.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the evidences list" do
      Evidence.stub(:find) { mock_evidence }
      delete :destroy, :id => "1"
      response.should redirect_to(evidences_url)
    end
  end

end
